### ISSUE TITLE
ShowPolicyPackage tool fails to run on java 9

### ISSUE THREAD

**Issue by polarfish** [CheckPointSW/ShowPolicyPackage#9]
The JAXB APIs are considered to be Java EE APIs, and therefore are no longer contained on the default class path in Java SE 9.

```
[d:\temp] java -jar "web_api_show_package-jar-with-dependencies.jar" -r -m 192.0.2.1
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
        at com.checkpoint.mgmt_api.client.FingerprintManager.getThumbPrint(FingerprintManager.java:376)
        at com.checkpoint.mgmt_api.client.FingerprintManager.getServerFingerprint(FingerprintManager.java:133)
        at com.checkpoint.mgmt_api.client.UtilClass.verifyServerFingerprint(UtilClass.java:134)
        at com.checkpoint.mgmt_api.client.UtilClass.verifyServerFingerprint(UtilClass.java:105)
        at com.checkpoint.mgmt_api.examples.ShowPackageTool.verifyServerFingerprint(ShowPackageTool.java:203)
        at com.checkpoint.mgmt_api.examples.ShowPackageTool.main(ShowPackageTool.java:119)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 6 more

[d:\temp]java -version
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

```

The version of the ShowPolicyPackage tool is 1.2.2

**Comment by polarfish** [comment]
The same behavior for java 10
```
[d:\temp] java -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
```
